import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import KeyboardNavigation from "@/components/KeyboardNavigation";
import LoadingBar from "@/components/LoadingBar";
import Navigation from "@/components/Navigation";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} antialiased font-mono bg-[#0a0a0a]`}
      >
        <LoadingBar />
        <KeyboardNavigation />
        <div className="max-w-[800px] mx-auto pb-24">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
